### ISSUE TITLE
Change Timezone to EST

### ISSUE THREAD

**Issue by Julien-Cousineau** [Julien-Cousineau/MNRF#1]
The current timezone is GMT. Change the api url to EST if possible.

**Comment by rywhale** [comment]
From the KiWIS API docs:

timezone --> the time zone that will be returned for all timestamps, any time zone string as understood by Java (e.g. GMT+5, UTC, CET) or 'individual' to use individual timeseries timezones

So you have have to append &timezone=EST to the end of the query URL. 

e.g. 
http://204.41.16.133/KiWIS/KiWIS?service=kisters&type=queryServices&request=getTimeseriesValues&datasource=0&format=html&ts_id=948603042&timezone=EST

**Comment by Julien-Cousineau** [comment]
I like the solution, however the KiWIS does not change automatically EST to EDT.
Another solution is to convert GMT to web browser timezone, this would solve the EST and EDT issue.

**Comment by Julien-Cousineau** [comment]
The app will show the data based on the client's (web browser) timezone.
