### ISSUE TITLE
Create RADARSAT Table

### ISSUE THREAD

**Issue by rywhale** [Julien-Cousineau/MNRF#15]
1) Not sure if you've already done this but the _most recent_ RADARSAT image should be the one that plots on the map first. 
Two ways you could do this: 

- Parse date from filename (probably not a great idea in case the naming changes)
- Organize the images by the date we upload them (e.g.- the most recently uploaded image gets displayed first)

2) We'll also want to make sure to clear all of the ones we've uploaded so far. This can probably wait until you move to the production server

**Comment by Julien-Cousineau** [comment]
@rywhale 
1. Right now, the Radarsat images are parsed by the date from the filename. 
Organizing the images by the uploaded date will be more complicated.
Is this necessary?

2. I don't like the dropdown list for the Radarsat. Once you get 10+ images, the list will be very long.
Please let me know if you have ideas.
I could have a dropdown list with the latest 5 and have a "more" option. The "more" option would be a popup with table.

**Comment by rywhale** [comment]
1) I'm ultimately fine with parsing the date from the filename, we just need to make it clear in the documentation that _the file naming must follow this convention_ so as to avoid this breaking in the future

2) I'm good with this idea, let's roll with it.

**Comment by Julien-Cousineau** [comment]
@rywhale 
Created the table. 
The legend is not the greatest since the name is so long. I'm open for suggestions.
![screenshot 2018-03-15 at 22 29 49](https://user-images.githubusercontent.com/22058563/37500544-6b642418-28a0-11e8-9d2d-acca6c6dba8b.png)

**Comment by rywhale** [comment]
@Julien-Cousineau Two things:

1. So we're actually thinking about standardizing the RADARSAT naming to something shorter. 
I think we're going to go with 
LOCATION_YYYY_MM_DD
e.g.
AlbanyForks_2017_03_15

This will make the selector easier on the eyes I think but might require you to tweak the code that parses the date from the filename. I will upload one last example file with the new naming convention a little later today. 

2. Can you change the name on the map legend from 'Radarsat' to 'Ice Conditions'? We're also working on some sort of disclaimer for this product.

**Comment by rywhale** [comment]
I uploaded an image with the new file naming convention for you

"AlbanyRiver_201705_09.tif" 

and now the selector is gone... Hopefully I didn't break it haha.

**Comment by Julien-Cousineau** [comment]
You did...kinda...the app is not able to parse the date properly.

**Comment by Julien-Cousineau** [comment]
Now it works for:
AlbanyRiver_2018_03_17.tif
AlbanyRiver_201705_09.tif
RiverIceBreakupClassification_ON_AlbanyRiver_20170502_231318
