### ISSUE TITLE
Add Ability to Toggle Past Gauge Photos (LOW PRIORITY)

### ISSUE THREAD

**Issue by rywhale** [Julien-Cousineau/MNRF#16]
If you have some time, maybe look into the possibility of adding selectors below the gauge photos to toggle back through previous photos. This is not essential so don't spend too much time if it's difficult.

**Comment by Julien-Cousineau** [comment]
That would be cool. I'll wait for this one.

**Comment by Julien-Cousineau** [comment]
Should be possible to link it with the WMS time scale.
