### ISSUE TITLE
Precipitation Data from KIWIS

### ISSUE THREAD

**Issue by Julien-Cousineau** [Julien-Cousineau/MNRF#17]
1. Add point on Map
2. Add to dashboard (download and create plot)

**Comment by Julien-Cousineau** [comment]
Nearby climate station as a proxy for precip. The best station is probably Moosonee RCS (station id 131136 in kiwis). If you could find some space for this graph that would be great. You might also consider having a button to show/hide the precip graph.

**Comment by rywhale** [comment]
Personally, I think this is realllly low on the priority list. The WMS layer does a good enough job approximating precip for the area.
