### ISSUE TITLE
Gauge Thresholds Incorrect 

### ISSUE THREAD

**Issue by rywhale** [Julien-Cousineau/MNRF#21]
You have threshold lines for the Fishing Creek gauge but there are no thresholds for that gauge.

Here's Andy's original message with the thresholds again:

Albany River above Fishing Creek Island (gauge cam)(No Thresholds)
Albany River near Hat Island (gauge cam) (LVL: 3.3, 4.29, 5.14, 5.9) (Flow:1500, 3000, 4500, 6000)
Stooping River above the Mouth (gauge cam) (No Thresholds)
Albany River above Nottick Island (No Thresholds)
Kenagami River near Mammamattawa (LVL: 23.5, 25, 26.5, 28) (Flow: No Flow thresholds)
Pagwachuan River at Hwy 11 (LVL: 10.98, 12.65, 14.33, 16.0) (Flow: 101.5, 203, 304, 406)
Nagagami River at Hwy 11 (LVL: 2.75, 3.15, 3.45, 3.7, 3.99)(Flow: 40, 135, 200, 250)
Little Current River at Percy Lake (No Thresholds)

Please double-check that the threshold lines are correct for applicable stations.

**Comment by Julien-Cousineau** [comment]
Switch Albany River above Fishing Creek Island and Albany River near Hat Island.
Should be fixed now.
