### ISSUE TITLE
Indicate Precip Source

### ISSUE THREAD

**Issue by beatonan** [Julien-Cousineau/MNRF#22]
![image](https://user-images.githubusercontent.com/36272704/37487294-7eb26f90-2867-11e8-8439-1b2aac50a029.png)

We should add some sort of indication as to where the precip data is coming from (e.g. Moosonee RCS). 

Could change 'Precip' to 'Precip Moosonee RCS'

This should be done for each plot.

**Comment by Julien-Cousineau** [comment]
Here's the change...not sure if that's the best location to add the station name. We could change the location in the future.
![screenshot 2018-03-21 at 22 25 01](https://user-images.githubusercontent.com/22058563/37747681-b9985ca2-2d56-11e8-9bf6-43f2fb1edbe5.png)

**Comment by beatonan** [comment]
looks good.  more explicit now as to what is being shown anyways.
