### ISSUE TITLE
Provide WMS Details

### ISSUE THREAD

**Issue by beatonan** [Julien-Cousineau/MNRF#23]
Specifically, that the WMS layer shows the past 24 hours cumulative precipitation prior to timestamp. 

E.g. if the timestamp is  2018-03-15T12:00:00Z
the data = 2018-03-1412:00:00Z --> 2018-03-15T12:00:00Z

If the time-slider for the precip is going to stay it would be good to add some text to indicate that the time slider controls the precipitation data

Should also include a link with info about the source (https://weather.gc.ca/grib/grib2_RDPA_ps10km_e.html).

**Comment by Julien-Cousineau** [comment]
@beatonan 
Moved the slider and text in the legend.
![screenshot 2018-03-21 at 22 06 46](https://user-images.githubusercontent.com/22058563/37747159-30c63f4a-2d54-11e8-8134-e23d37015e07.png)

Please let me know if this does the trick for now.

**Comment by beatonan** [comment]
this is much better and more clear as to the data source that relates to the time slider.  A minor point, it takes quite a bit of dexterity to go back or forward a day using the slider.  If easily possible, it would be good to try to resolve this with a forward and backward arrow button or something.  If not a simple solution, don't worry about it.
