### ISSUE TITLE
Site Branding

### ISSUE THREAD

**Issue by beatonan** [Julien-Cousineau/MNRF#26]
It would be much better if the site was branded as a collaborative effort between NRC and MNRF by including NRC logo or something within the banner.  We have an Ontario.ca website that Provincial information flows through.  There may be confusion as to why this site is not an ontario.ca site but it is branded by a Provincial Ministry (MNRF).  Having dual branding (MNRF and NRC) may help resolve clarify this confusion.

**Comment by Julien-Cousineau** [comment]
@beatonan The production server will have this default name: mnrmap-appsrvr.canadaeast.cloudapp.azure.com. Very ugly.

However, we can change it to anything that we want that is available.
For example: ontario-fnd.ca (fnd=Far North Dashboard)
You can check at https://www.webnames.ca/

I'll leave this up to you.

**Comment by beatonan** [comment]
looks like "ontario-fnd.ca" is available and looks good to me.
