### ISSUE TITLE
resolution of y axis for a few of the gauges 

### ISSUE THREAD

**Issue by beatonan** [Julien-Cousineau/MNRF#27]
the level and flow graphs look a bit funny (flat lined) for a few of the gauges at the 1 week and sometimes the 1 month time interval.  The time-series graphs do not look the same as they do here.  I think this is because the resolution of the y axis is too small so that the variability at the smaller time intervals is being rounded. 

Possible to increase the resolution (number of decimal places) of the y axis for the:
Hat Island,
Kenagami,
Pagachuwan,
Nagagami,
Percy Lake Gauges

Would be ideal if the data were displayed to several decimal places but the y axis labeling only showed a couple of digits.

example from hat island gauge in our data:

![image](https://user-images.githubusercontent.com/36272704/37774458-a72ce4d8-2db6-11e8-8690-61a6f68dab2c.png)

**Comment by Julien-Cousineau** [comment]
It seems to be rounding to the nearest centimeter. I'll try to change that to the nearest millimeter.

**Comment by Julien-Cousineau** [comment]
@beatonan It seems the application is downloading water level to the nearest centimeter.
I've added the parameter (useprecision=false) in the API request and seems to do the trick.
