### ISSUE TITLE
indicate somewhere that the tabs with rivers other than Albany are incomplete

### ISSUE THREAD

**Issue by beatonan** [Julien-Cousineau/MNRF#28]
if the tabs for the rivers other than Albany are going to stay on the page, would be good to indicate somewhere that they are under construction and data are incomplete.  I think it is good to keep these as they do still provide valuable information but don't want people to be confused and think that is the only info available for these rivers or wonder why other information that they know exists is omitted.

**Comment by Julien-Cousineau** [comment]
I've added "Under Construction".
If it's causing issues, please let me know and I'll remove the "under construction" rivers.
