### ISSUE TITLE
Map Labels / Legend

### ISSUE THREAD

**Issue by rywhale** [Julien-Cousineau/MNRF#3]
We'll need to add some sort of legend or labels to differentiate the stations in the header map (currently just points).

**Comment by rywhale** [comment]
Will also need a legend for the precip data if we decide to leave it on the map.

**Comment by Julien-Cousineau** [comment]
Agree. I'll be working in the GUI part soon.

**Comment by Julien-Cousineau** [comment]
It's not perfect but it's a start:
Radarsat or Ice (static image)
![image](https://user-images.githubusercontent.com/22058563/36611266-e3c77ac8-18a0-11e8-960b-c112c67820fe.png)

Precip (static image)
![image](https://user-images.githubusercontent.com/22058563/36611314-095202b8-18a1-11e8-9b49-c6ebd939851d.png)

**Comment by Julien-Cousineau** [comment]
Convert images to html
