### ISSUE TITLE
KIWIS server not available

### ISSUE THREAD

**Issue by Julien-Cousineau** [Julien-Cousineau/MNRF#34]
KIWIS is sometimes not available and unable to to obtain timeseries.
I could save the data (make a copy) on the server.

**Comment by rywhale** [comment]
Hey Julien, the permanent address for the SWMC KiWIS is now

https://www.swmc.mnr.gov.on.ca/KiWIS/KiWIS?

I was told that the old IP would keep working but it's possible that's not the case. Might want to consider using the new URL just in case.

**Comment by Julien-Cousineau** [comment]
Thanks! I'll try it right now.
