### ISSUE TITLE
Gauge Photo Captions

### ISSUE THREAD

**Issue by rywhale** [Julien-Cousineau/MNRF#4]
Each gauge photo should have a caption with the date (you can get this from the Flickr API). The upload date will be the same as the date the photo was taken.

**Comment by Julien-Cousineau** [comment]
Sure. Do you want the same date as in the filename? (i.e 04FC001_Attawapiskat_Rv_20180203150108.jpg)

**Comment by rywhale** [comment]
Nah, we just need the date really.

Something like:

> Photo Taken 2018-02-03 15:01:08

I believe you can also get the photo upload date from the Flickr API (instead of parsing the filename).

**Comment by Julien-Cousineau** [comment]
Label was taken from the filename. Example: 04FC001_Attawapiskat_Rv_20180203150108.jpg => Photo Taken 2018-02-03 15:01:08

I'm trying to avoid making another call to the API.
