### ISSUE TITLE
Scale Y-Axis in TS Plots Dynamically 

### ISSUE THREAD

**Issue by rywhale** [Julien-Cousineau/MNRF#6]
The Y-Axis on the time series plots should scale dynamically to the min/max of the values when you change the time period. 

Currently we go from 

![pre_scale](https://user-images.githubusercontent.com/33959166/36424930-0fb7b020-1613-11e8-93bc-9e8847b47995.JPG)

to

![post_scale](https://user-images.githubusercontent.com/33959166/36424939-1657d036-1613-11e8-808e-ddcea96ea76a.JPG)

The scale needs to change in the second plot or the data isn't readable.

**Comment by Julien-Cousineau** [comment]
I'm not too sure I understand. Would the second plot Y-axis be between 2.46 and 2.5?

**Comment by rywhale** [comment]
Yeah, the Y-axis in the second plot should scale to the min/max of the data in the second plot. In other words, every time you change the time range with one of the selectors (all, 6m, 1m, 1w), the Y-axis should automatically scale to the min/max values in the time range. 

So if the min/max in the second plot are 2.46/2.5 you would scale to those values. The issue is that the second plot looks flat when in reality there is still some fluctuation going on there

**Comment by Julien-Cousineau** [comment]
I'll look into it. The Plotly library is nice but customization can be a pain.

**Comment by beatonan** [comment]
@Julien-Cousineau we see the scaling of y-axis is a pretty high priority vs other issues so would be great if this could get some focus.

**Comment by Julien-Cousineau** [comment]
From plotly:https://github.com/plotly/plotly.js/issues/1876
The axis auto-range is currently not available.

Possible temporary solution:
Hard code y-axis based on selected data.
1. Add clicking event
2. filter data based on selected button
3. find min max
4. adjust graph

**Comment by Julien-Cousineau** [comment]
My temporary code seems to be working however, the range slider at the bottom use the same y-axis as the chart as shown below. Please let me know if that is an issue.
![screenshot 2018-03-15 at 19 14 48](https://user-images.githubusercontent.com/22058563/37495787-64e165d0-2885-11e8-8275-7c354f70ebf5.png)

**Comment by rywhale** [comment]
@Julien-Cousineau Looks good to me

**Comment by Cevior** [comment]
Could you provide some (coding-) details on how you solved it? Would it be possible to integrate it via [event handlers](https://plotly-r.com/js-event-handlers.html) in R?
