### ISSUE TITLE
Units for Discharge Values

### ISSUE THREAD

**Issue by rywhale** [Julien-Cousineau/MNRF#7]
Discharge is measured in 

cm/s 

or

m^3 / s

You can verify which it is by adding 

> &metadata=true&md_returnfields=ts_unitname

To the end of a query.

**Comment by Julien-Cousineau** [comment]
Thanks! I will add this to the code

**Comment by Julien-Cousineau** [comment]
Units:
For Level : meter = > m
For Discharge : cubic meter per second = >m<sup>3</sup>/s
For Precip: ??? Have not tested
