### ISSUE TITLE
Clarify 'All' Selector in TS Graphs

### ISSUE THREAD

**Issue by rywhale** [Julien-Cousineau/MNRF#8]
It looks like clicking the 'All' time selector gives the last 9 months of data. Probably worth clarifying this since the past 9 months is definitely not _all_ the data.

Not sure if it's possible to change the 'All' label with the plotting API you're using. If not, maybe we add a disclaimer that 'All' = 9 months or whatever.

**Comment by Julien-Cousineau** [comment]
Agree. I believe the "all" is just the default label. Right now, I'm retrieving data in the last 9 months, which we might want to change.
I might to some testing: I might dowload LVL.1.O in the last month and download LVL.daymean in the last year.

**Comment by Julien-Cousineau** [comment]
The app is now only getting information for the last 6 months.
Change to 6m, 1m and 1w.
![image](https://user-images.githubusercontent.com/22058563/37291052-3ab5b5d4-25e4-11e8-8ff5-f8cc8c15b26d.png)
